[package]
name = "compiler"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "A compiler for the OCR Reference Language"
authors = ["DrBracewell"]
repository = "https://github.com/DoctorBracewell/ocr-compiler/tree/main/packages/rust-compiler"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
wasm-bindgen = "0.2.80"